### PR TITLE
Refactoring some code

### PR DESCRIPTION
**Pull request by sunaoka**
The following has been fixed.
Please review them.

- Corrected PHPDoc block.
- Optimize imports.
- Update phpstan.neon
- Run style checks and fixed violations (composer fix-style).
- Add ext-json to composer.json.
- Remove atoum/atoum.
- Optimized loading of configuration files.

### All Submissions:

* [x] Have you followed the guidelines in our [Contributing](../../paypayopa-sdk-php/blob/master/contributing.md) document?
* [x] Have you read and signed the automated Contributor's License Agreement?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../paypayopa-sdk-php/pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by shreyanshp — COMMENTED** [review]
Overall looks good, great job @sunaoka 
Could you please try to resolve the quality gate issues so that we have all green for merging this PR
https://sonarcloud.io/project/issues?id=paypay_paypayopa-sdk-php&pullRequest=102&resolved=false&types=CODE_SMELL

**Comment by sunaoka** [comment]
> Could you please try to resolve the quality gate issues so that we have all green for merging this PR
> https://sonarcloud.io/project/issues?id=paypay_paypayopa-sdk-php&pullRequest=102&resolved=false&types=CODE_SMELL

@shreyanshp 
I removed the empty statement.

However, the "2 duplicated blocks of code must be removed" has not been resolved. There are no duplicated blocks.
<https://sonarcloud.io/project/issues?id=paypay_paypayopa-sdk-php&issues=AXb1c-eNzNzWtWba8r0s&open=AXb1c-eNzNzWtWba8r0s&pullRequest=102>

**Review by shreyanshp — APPROVED** [review]

**Comment by shreyanshp** [comment]
@sunaoka Looks good, thank you for the PR, glad to have you!

**Comment by shreyanshp** [comment]
closes #99

**Pull request merged**
