### PR TITLE
Deleted composer.lock

### LINKED ISSUE #25: composer.lock is redundant for libraries
This library includes `composer.lock` which is:

- Not used when installing any library with Composer. [It's just outright ignored.](https://getcomposer.org/doc/02-libraries.md#lock-file)
- It hinders testing under different versions of dependencies. Say, Travis CI would normally do `composer install` for you during CI, with `composer.lock` present you would have to do `composer update` additionally. Likewise, contributors would have to do that too.
- It pollutes `composer.json` update diffs, since they both have to be updated.

There's no point to keep it committed in a library, on the contrary with a deployable project, which this project is not.

[Here's what the documentation says](https://getcomposer.org/doc/02-libraries.md#lock-file):

> However, this lock file will not have any effect on other projects that depend on it. It only has an effect on the main project.

### PR DESCRIPTION
**Pull request by sanmai**
As per #20

Fixes #25

### CODE REVIEW

**Review by paypay-ayas — COMMENTED** [review]
@sanmai  It is necessary for us to maintain lockfiles for SDKs as we have to maintain stability across systems. Lock files let us know which combination of dependencies contributed to the last successful build of our package. By keeping the lock file we are keeping the responsibility of stability on the maintainers which should be the case for SDKs of any kind. 

Here is [an article](https://levelup.gitconnected.com/package-lock-json-and-yarn-lock-are-your-best-friends-7ec63c24fbe5) that talks about this at length. the article talks about npm/yarn packages but the same may be applied to composer as well. 

Thank you for actively contributing to the codebase. We look forward to your future contributions. Feel free to report issues and we will do our best to resolve it.

**Comment by shreyanshp** [comment]
@sanmai and @paypay-ayas The lock files would help contributors of the SDK be aware of which dependency library version was used to build/test the SDK, which I think we should communicate

It would have no impact on consumers of the SDK, who would have their own composer.json, which is good thing either way, I know it makes the PR ugly, and for these two reason I was fine with removing the lock file, however let's think about what benefits it brings to the contributors,

**Comment by sanmai** [comment]
See, it completely right to keep `composer.lock` for a _deployable_ project (as in `docker build` deployable) for all the right reasons (maintain stability etc.), but for a _library_ it makes more harm than good because your job as a library maintainer is the complete opposite. As a library maintainer you have to be proactive in terms of newer versions of dependencies.

Consider that this library [depends on firebase/php-jwt](https://github.com/paypay/paypayopa-sdk-php/blob/3cfcd87fb705dc0c5b52e29b8619a57b3fd55abc/composer.json#L41) with version constraint set to `^5.2`, and let's say you have a committed composer.lock with the above version which basically means that Composer won't try install any other version. This version constraint of `^5.2` is unbound, e.g. it permits installing this library with future versions of `firebase/php-jwt` (up to a limit). 

Now, imagine there's a newer version of `firebase/php-jwt` at some point in the future, say 5.9, which is happen to be incompatible with this library (by causing sporadic failures). And then someone runs `composer require paypayopa/php-sdk` at about time, and Composer will naturally try to install the newest version of `firebase/php-jwt` like it does. 

Now you have a very unpleasant situation where your valuable customer has to pick their hairs out because they can't process payments for some very vague reasons, and they call your boss's boss to call you in the night because there's _a problem_ in your library. Nobody would want to be in your shoes then!

But _if_ you didn't have `composer.lock` committed, you _would_ have tested the library with a daily or a PR build with the most recent version of `firebase/php-jwt` (because that's what `composer install` does without .lock: installs most recent deps), you _would_ have found the problem, and you _would_ have fixed it even before it affected the customer. You would have completely dodged the bullet and saved your night's sleep.

Makes sense?

**Comment by sanmai** [comment]
> The lock files would help contributors of the SDK be aware of which dependency library version was used to build/test the SDK

`composer.json` does that just as well, in a more convenient human-readable form. 

(There are some issues with how `composer.json` is currently designed, but let's not just too far, and try to focus on the problem we have where on hand. I will try to fix these problems once we deal with this issue.)

**Comment by shreyanshp** [comment]
@sanmai The consumer's lock file or composer.json will be completely separate and something that I don't we could control. Consumer can decide to install whatever dependency he/she wants for their projects be it older or latest version

I completely agree with building this SDK project itself with latest dependencies always, I think that's already taken care of by dependabot, you can refer previous PRs, making sure the SDK project uses the latest version always

These are all valid points from both @sanmai and @paypay-ayas , I think it should be discussed on Slack, which would setup by this weekend, as I don't think PRs and Issues are the best medium for discussing these issues and trust we are aware of the issues we have with the SDK, not just the lock file, it would need some rearch as well 😅

**Comment by sanmai** [comment]
@shreyanshp Well, not exactly so. Your `composer.json` is what you control, and consumers have to abide by the rules set in your `composer.json`. For example, if you say in `composer.json` that you package only to be installed with _exactly_ these versions of dependencies (`=5.2`), that's what will be for anyone trying to install the package with `composer require`. 

The problem here is not that you can't control the dependencies, but rather that setting exact versions of dependencies is not in your best interest. Say, there's a security patch for `firebase/php-jwt` with a version bumped to `5.2.1`, you want your customers to be able to upgrade without needing you to release an update.

These Dependabot PRs give you an illusion of control, because you may think like, okay, this build for this new version bump PR is broken, surely this means our master branch is it not? Can't it wait? And then you'll be wrong because it is, in fact, broken already. Much better would be as explicit and transparent as possible here by scheduling daily builds, which you can do with Travis CI. Again, let's recall that we're dealing here with a leading payment processing company in Japan. How much liberty do you have? What is the price of a mistake? Can you take shortcuts?.. I have an impression that you don't.

I have only as much time to help you out, let's make it worth it.

**Comment by shreyanshp** [comment]
@sanmai My sincerest apologies for the delay in revert
You can use the below link to sign up for our Open Source Slack
https://paypaydevlopers-slack.herokuapp.com/

Apart from the above, I believe having a lock file helps in long run and specially when we have multiple people working on same repo
As for the point of using old package/library version, I believe that gets solved by dependabot 

I will close this for now, feel free to join the slack and let us know your thoughts!

**Pull request closed without merging**
